title = "Rowan Clarke"
theme = "holy"
assetsDir = "/assets/"
[menu]
[[menu.main]]
  identifier = "series"
  name = "Series"
  url = "/series/"
  weight = 8
[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
